FQhStatsKeepr/FQhStatsKeepr/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include ('main.urls')),
    path('admin/', admin.site.urls),
]

FQhStatsKeepr/main/urls.py
from django.urls import path
from . import views



app_name = 'main' #namespace



urlpatterns = [
	path ("", views.homepage, name = "homepage"),
	path ("newGame/", views.newGame, name = "newGame"),
	path ("gamePlay/", views.gamePlay, name = "gamePlay"),
	path ("endGame/", views.endGame, name = "endGame"),
	path ("playerStats/", views.playerStats, name = "playerStats"),
]

FQhStatsKeepr/main/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Game (models.Model):
	teamRed_score = models.IntegerField()
	teamBlue_score = models.IntegerField()
	teamRed_players = models.JSONField()
	teamBlue_players = models.JSONField()
	teamRed_indexPlayerGoalsandAssist = models.JSONField()
	teamBlue_indexPlayerGoalsandAssist = models.JSONField()
	game_Complete = models.BooleanField(default = False)
	game_Date = models.DateField ('date Played')
	game_code = models.CharField(max_length = 100, default = '')

	def __str__(self):
		return str(self.game_Date)

class Players(models.Model):
	player_name = models.CharField (max_length = 200)
	player_lifeTimeGoals = models.IntegerField()
	player_lifeTimeAssists = models.IntegerField()
	player_lifeTimeScore = models.IntegerField()
	

	def __str__(self):
		return self.player_name

# class Games(models.Model):
# 	game_Date = models.ForiegnKey(Game, default = 1, verbose_name = "Date", on_delete = models.SET_DEFAULT)

FQhStatsKeepr/main/forms.py
from django import forms
import datetime

class newGameForm (forms.Form):
	redPlayer1 = forms.CharField (label= 'Red Captain', max_length = 100, initial = "", required = True) #required
	redPlayer2 = forms.CharField (label= 'Red Player 2', max_length = 100, initial = "", required = False) #required
	redPlayer3 = forms.CharField (label= 'Red Player 3', max_length = 100, initial = "", required = False) #required
	redPlayer4 = forms.CharField (label= 'Red Player 4', max_length = 100, initial = "", required = False) #required
	redPlayer5 = forms.CharField (label= 'Red Player 5', max_length = 100, initial = "", required = False)
	redPlayer6 = forms.CharField (label= 'Red Player 6', max_length = 100, initial = "", required = False)
	redPlayer7 = forms.CharField (label= 'Red Player 7', max_length = 100, initial = "", required = False)
	redPlayer8 = forms.CharField (label= 'Red Player 8', max_length = 100, initial = "", required = False)
	redPlayer9 = forms.CharField (label= 'Red Player 9', max_length = 100, initial = "", required = False)
	redPlayer10 = forms.CharField (label= 'Red Goalie', max_length = 100, initial = "", required = True)

	bluePlayer1 = forms.CharField (label= 'Blue Captain', max_length = 100, initial = "", required = True) #required
	bluePlayer2 = forms.CharField (label= 'Blue Player 2', max_length = 100, initial = "", required = False) #required
	bluePlayer3 = forms.CharField (label= 'Blue Player 3', max_length = 100, initial = "", required = False) #required
	bluePlayer4 = forms.CharField (label= 'Blue Player 4', max_length = 100, initial = "", required = False) #required
	bluePlayer5 = forms.CharField (label= 'Blue Player 5', max_length = 100, initial = "", required = False)
	bluePlayer6 = forms.CharField (label= 'Blue Player 6', max_length = 100, initial = "", required = False)
	bluePlayer7 = forms.CharField (label= 'Blue Player 7', max_length = 100, initial = "", required = False)
	bluePlayer8 = forms.CharField (label= 'Blue Player 8', max_length = 100, initial = "", required = False)
	bluePlayer9 = forms.CharField (label= 'Blue Player 9', max_length = 100, initial = "", required = False)
	bluePlayer10 = forms.CharField (label= 'Blue Goalie', max_length = 100, initial = "", required = True)

	game_Date = forms.DateField(initial = datetime.date.today) 


class gamePlayForm(forms.Form):
	nothing= forms.CharField(label='',required = False)
	

FQhStatsKeepr/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Game, Players
from .forms import newGameForm, gamePlayForm
from django.views.decorators.csrf import csrf_exempt,csrf_protect 
import json,random, string
from django.urls import reverse
from urllib.parse import urlencode

def homepage(request):
    return render (request = request,
                   template_name = 'main/home.html',
                   context = {"Games":Game.objects.all,
                              "Players": Players.objects.all})

def newGame (request):
 # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = newGameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            newGameInstance = Game()
            # playersInstance = Players() ##gotta do something about this...
            redPlayers = {}
            redPlayers_GoalsAssists = {}
            bluePlayers = {}
            bluePlayers_GoalsAssists = {}
            game_Date = form.cleaned_data.get("game_Date")
            for k, v in form.data.items():
                if k.find("red") > -1:
                    if v:
                        redPlayers[k] = v
                        redPlayers_GoalsAssists[v]={"goals": 0,
                                        "assists": 0}
                if k.find("blue") > -1:
                    if v:
                        bluePlayers[k] = v
                        bluePlayers_GoalsAssists[v]={"goals": 0,
                                        "assists": 0}

            newGameInstance.teamRed_players = redPlayers
            newGameInstance.teamBlue_players = bluePlayers
            newGameInstance.game_Date = game_Date
            newGameInstance.teamRed_indexPlayerGoalsandAssist = redPlayers_GoalsAssists
            newGameInstance.teamBlue_indexPlayerGoalsandAssist = bluePlayers_GoalsAssists
            newGameInstance.teamBlue_score = 0
            newGameInstance.teamRed_score = 0 
            newGameInstance.game_Complete = False
            newGameInstance.game_code = ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(20))
            newGameInstance.save()
           
            base_url = "/gamePlay"
            gameCode_url = urlencode({'gameCode': newGameInstance.game_code})
            url_additive = '{}?{}'.format(base_url,gameCode_url)
            print (url_additive)
            return redirect(url_additive)
        print(form.errors)
        return redirect("/newGame")
    else:
        form = newGameForm()

        return render(request = request, template_name = 'main/newGame.html', context = {'form': form})


@csrf_exempt
def gamePlay (request):

    if request.method == 'POST':
        data = json.loads (request.body)
        redTeam = data['redTeam']
        blueTeam = data['blueTeam']
        gameInstance = Game.objects.get(game_code__exact= data['gameCode'])

        for i, players in enumerate(redTeam):
            gameInstance.teamRed_score += int(players['Goals'])
            gameInstance.teamRed_indexPlayerGoalsandAssist[players['player_name']] = {'goals': players['Goals'], 'assists': players ['Assists']}




        for i, players in enumerate(blueTeam):
            gameInstance.teamBlue_score += int(players['Goals'])
            gameInstance.teamBlue_indexPlayerGoalsandAssist[players['player_name']] = {'goals': players['Goals'], 'assists': players ['Assists']}
            
        print(gameInstance.teamRed_indexPlayerGoalsandAssist)
        
        gameInstance.game_Complete = True
        gameInstance.save()

        base_url = "/endGame"
        gameCode_url = urlencode({'gameCode': gameInstance.game_code})
        url_additive = '{}?{}'.format(base_url, gameCode_url)

        return redirect(url_additive)

    else:

        gameCode  = request.GET.get('gameCode');
        gameInstance = Game.objects.get(game_code__exact = gameCode)

        if gameInstance.game_Complete == False:
            return render(request = request,
                            template_name = 'main/gamePlay.html',
                            context = {"Game": gameInstance})
        else:
            base_url = "/endGame"
            gameCode_url = urlencode({'gameCode': gameInstance.game_code})
            url_additive = '{}?{}'.format(base_url, gameCode_url)
            return redirect(url_additive)

@csrf_exempt
def endGame(request):
    gameCode  = request.GET.get('gameCode');
    gameInstance = Game.objects.get(game_code__exact = gameCode)
    redTeamPlayers = gameInstance.teamRed_players
    blueTeamPlayers = gameInstance.teamBlue_players

    wholeRed = reStructure(redTeamPlayers,gameInstance.teamRed_indexPlayerGoalsandAssist)
    wholeBlue = reStructure(blueTeamPlayers,gameInstance.teamBlue_indexPlayerGoalsandAssist)
    print(wholeRed)
    
    return render(request = request, 
                template_name='main/endGame.html', 
                context = {'Game': gameInstance,
                            'wholeRed':wholeRed, 'wholeBlue': wholeBlue})

def reStructure(colorTeamPlayers, IndexedGoalsandAssists):
    structuredDict={}
    # print(colorTeamPlayers)
    # print (IndexedGoalsandAssists)
    for k,v in colorTeamPlayers.items():
        structuredDict[k] = {'Name': v, 
                            'goals': IndexedGoalsandAssists[v]['goals'], 
                            'assists' : IndexedGoalsandAssists[v]['assists'],
                            'points': int(IndexedGoalsandAssists[v]['goals']) + int(IndexedGoalsandAssists[v]['assists'])}
    
    return structuredDict 

def playerStats(request):
    return render(request = request,
                        template_name = 'main/playerStats.html',
                        context = {})

FQhStatsKeepr/main/templates/main/gamePlay.html
{% extends 'main/header.html' %}

{% block content %}

<script>
	var redTeam = [];
	var blueTeam = [];

	function udpateScores(player_name, goals, assists, teamRoster) {
		var teamRosterRevised = []
		if (teamRoster.length > 0) {
			i = 0
			for (z = 0; z < teamRoster.length; z++) {
				if (player_name != teamRoster[z]['player_name']) {
					teamRosterRevised[i] = teamRoster[z]
					i++;
				}
			}
			teamRoster = teamRosterRevised
		}
		teamRoster.push({ player_name: player_name, 'Goals': goals, 'Assists': assists });
		return teamRoster

	}
</script>


<style>
	.center {
		border: 5px;
		display: flex;
		justify-content: center;
	}

	.TotalBlue {
		font-size: 50px;
	}

	.TotalRed {
		font-size: 50px;
	}
</style>

<div class="center">
	<div class="card-panel red darken-1">
		<span class="white-text">
			Red Score
			<div class="TotalRed">0</div>
		</span>
	</div>
	&nbsp;&nbsp;&nbsp;
	<div class="card-panel blue darken-1">
		<span class="white-text">
			Blue Score
			<div class="TotalBlue">0</div>
		</span>
	</div>

</div>


</div>
<div class="row">
	<div class="col s6">
		<div class="container">
			<h5><span class ="red-text text-darken-2">Red Team</span></h5>
			{% for position, players in Game.teamRed_players.items %}
			{% if forloop.counter == Game.teamRed_players.items|length %}
			<br><br>	
			<div class = "divider"></div>
			{% endif %}
			<p>{{players}}</p>
			<style>
				.R_counter_ {
						{
						forloop.counter
					}
				}

					{
					font-size: 24px;
					border-radius: 9%;
				}

				.R_counter2_ {
						{
						forloop.counter
					}
				}

					{
					font-size: 22px;
					border-radius: 9%;
				}
			</style>


			<div class="R_playerCounter">
				<span class="new badge orange" data-badge-caption="">
					<div class="R_counter2_{{forloop.counter}}"> 0 </div>
				</span>
				<span class="new badge green" data-badge-caption="">
					<div class="R_counter_{{forloop.counter}}"> 0 </div>
				</span>


			</div>
			<div class="buttons text-center">
				<a class="waves-effect waves-light btn">
					<div class="R_addp_{{forloop.counter}}">add point</div>
				</a>
				<a class="waves-effect waves-light btn">
					<div class="R_adda_{{forloop.counter}}">add assist</div>
				</a>
				<a class="waves-effect waves-light btn">
					<div class="R_minp_{{forloop.counter}}">minus point</div>
				</a>
				<a class="waves-effect waves-light btn">
					<div class="R_mina_{{forloop.counter}}">minus assist</div>
				</a>
			</div>

			<script type="text/javascript">
				let R_addp_{{ forloop.counter }} = document.querySelector(".R_addp_{{forloop.counter}}");
				let R_adda_{{ forloop.counter }} = document.querySelector(".R_adda_{{forloop.counter}}");
				let R_minp_{{ forloop.counter }} = document.querySelector(".R_minp_{{forloop.counter}}");
				let R_mina_{{ forloop.counter }} = document.querySelector(".R_mina_{{forloop.counter}}");
				let R_counter_{{ forloop.counter }} = document.querySelector(".R_counter_{{forloop.counter}}");
				let R_counter2_{{ forloop.counter }} = document.querySelector(".R_counter2_{{forloop.counter}}");


				R_addp_{{ forloop.counter }}.addEventListener('click', R_addp{{ forloop.counter }}_g);
				R_adda_{{ forloop.counter }}.addEventListener('click', R_addp_{{ forloop.counter }}_a);
				R_minp_{{ forloop.counter }}.addEventListener('click', R_minp_{{ forloop.counter }}_g);
				R_mina_{{ forloop.counter }}.addEventListener('click', R_minp_{{ forloop.counter }}_a);



				function R_addp{{forloop.counter}}_g(){
					counter_num = R_counter_{{forloop.counter}}.innerHTML
					totalRed = document.querySelector(".TotalRed").innerHTML

					R_counter_{{forloop.counter}}.innerHTML = parseInt(counter_num) + 1
					document.querySelector(".TotalRed").innerHTML = parseInt(totalRed) + 1
					
					redTeam = udpateScores("{{players}}",
						R_counter_{{ forloop.counter }}.innerHTML,
							R_counter2_{{forloop.counter}}.innerHTML, redTeam);
					
					console.log(redTeam);
				}

				function R_addp_{{forloop.counter}}_a(){
					counter_num = R_counter2_{{forloop.counter}}.innerHTML

					R_counter2_{{forloop.counter}}.innerHTML = parseInt(counter_num) + 1

					redTeam = udpateScores("{{players}}",
						R_counter_{{ forloop.counter }}.innerHTML,
							R_counter2_{{forloop.counter}}.innerHTML, redTeam)
				}

				function R_minp_{{forloop.counter}}_g(){
					counter_num = R_counter_{{forloop.counter}}.innerHTML
					totalRed = document.querySelector(".TotalRed").innerHTML
					if (counter_num == 0) {
						return false
					}
					R_counter_{{forloop.counter}}.innerHTML = parseInt(counter_num) - 1
					if (totalRed == 0) {
						return false
					}

					document.querySelector(".TotalRed").innerHTML = parseInt(totalRed) - 1

					redTeam = udpateScores("{{players}}",
						R_counter_{{ forloop.counter }}.innerHTML,
							R_counter2_{{forloop.counter}}.innerHTML, redTeam)
				}

				function R_minp_{{forloop.counter}}_a(){
					counter_num = R_counter2_{{forloop.counter}}.innerHTML
					if (counter_num == 0) {
						return false
					}
					R_counter2_{{forloop.counter}}.innerHTML = parseInt(counter_num) - 1

					redTeam = udpateScores("{{players}}",
						R_counter_{{ forloop.counter }}.innerHTML,
							R_counter2_{{forloop.counter}}.innerHTML, redTeam)
				}
			</script>

			{% endfor %}
		</div>
	</div>
	<div class="col s6">
		<div class="container">
			<h5><span class ="blue-text text-darken-2">Blue Team</span></h5>
			{% for position, players in Game.teamBlue_players.items %}
			{% if forloop.counter == Game.teamBlue_players.items|length %}
			<br><br>	
			<div class = "divider"></div>
			{% endif %}
			<p>{{players}}</p>
			<style>
				.B_counter_ {
						{
						forloop.counter
					}
				}

					{
					font-size: 25px;
					border-radius: 5%;
				}

				.B_counter2_ {
						{
						forloop.counter
					}
				}

					{
					font-size: 25px;
					border-radius: 5%;
				}
			</style>


				<div class="B_playerCounter">
					<span class="new badge orange" data-badge-caption="">
						<div class="B_counter2_{{forloop.counter}}"> 0 </div>
					</span>
					<span class="new badge green" data-badge-caption="">
						<div class="B_counter_{{forloop.counter}}"> 0 </div>
					</span>


				</div>
				<div class="buttons text-center">
					<a class="waves-effect waves-light btn">
						<div class="B_addp_{{forloop.counter}}">add point</div>
					</a>
					<a class="waves-effect waves-light btn">
						<div class="B_adda_{{forloop.counter}}">add assist</div>
					</a>
					<a class="waves-effect waves-light btn">
						<div class="B_minp_{{forloop.counter}}">minus point</div>
					</a>
					<a class="waves-effect waves-light btn">
						<div class="B_mina_{{forloop.counter}}">minus assist</div>
					</a>
				</div>

				<script type="text/javascript">
					let B_addp_{{ forloop.counter }} = document.querySelector(".B_addp_{{forloop.counter}}");
					let B_adda_{{ forloop.counter }} = document.querySelector(".B_adda_{{forloop.counter}}");
					let B_minp_{{ forloop.counter }} = document.querySelector(".B_minp_{{forloop.counter}}");
					let B_mina_{{ forloop.counter }} = document.querySelector(".B_mina_{{forloop.counter}}");
					let B_counter_{{ forloop.counter }} = document.querySelector(".B_counter_{{forloop.counter}}");
					let B_counter2_{{ forloop.counter }} = document.querySelector(".B_counter2_{{forloop.counter}}");


					B_addp_{{forloop.counter}}.addEventListener('click', B_addp{{ forloop.counter }}_g);
					B_adda_{{forloop.counter}}.addEventListener('click', B_addp_{{ forloop.counter }}_a);
					B_minp_{{forloop.counter}}.addEventListener('click', B_minp_{{ forloop.counter }}_g);
					B_mina_{{forloop.counter}}.addEventListener('click', B_minp_{{ forloop.counter }}_a);



					function B_addp{{forloop.counter}}_g(){
						counter_num = B_counter_{{forloop.counter}}.innerHTML
						totalBlue = document.querySelector(".TotalBlue").innerHTML

						B_counter_{{forloop.counter}}.innerHTML = parseInt(counter_num) + 1
						document.querySelector(".TotalBlue").innerHTML = parseInt(totalBlue) + 1


						blueTeam = udpateScores("{{players}}",
							B_counter_{{ forloop.counter }}.innerHTML,
								B_counter2_{{forloop.counter}}.innerHTML, blueTeam)					
					}

					function B_addp_{{forloop.counter}}_a(){
						counter_num = B_counter2_{{forloop.counter}}.innerHTML

						B_counter2_{{forloop.counter}}.innerHTML = parseInt(counter_num) + 1

						blueTeam = udpateScores("{{players}}",
							B_counter_{{ forloop.counter }}.innerHTML,
								B_counter2_{{forloop.counter}}.innerHTML, blueTeam)	
					}

					function B_minp_{{forloop.counter}}_g(){
						counter_num = B_counter_{{forloop.counter}}.innerHTML
						totalBlue = document.querySelector(".TotalBlue").innerHTML
						if (counter_num == 0) {
							return false
						}
						B_counter_{{forloop.counter}}.innerHTML = parseInt(counter_num) - 1
						if (totalBlue == 0) {
							return false
						}
						document.querySelector(".TotalBlue").innerHTML = parseInt(totalBlue) - 1

						blueTeam = udpateScores("{{players}}",
							B_counter_{{ forloop.counter }}.innerHTML,
								B_counter2_{{forloop.counter}}.innerHTML, blueTeam)	
					}

					function B_minp_{{forloop.counter}}_a(){
						counter_num = B_counter2_{{forloop.counter}}.innerHTML
						if (counter_num == 0) {
							return false
						}
						B_counter2_{{forloop.counter}}.innerHTML = parseInt(counter_num) - 1

						blueTeam = udpateScores("{{players}}",
							B_counter_{{ forloop.counter }}.innerHTML,
								B_counter2_{{forloop.counter}}.innerHTML, blueTeam)	
					}
				</script>
			{% endfor %}
		</div>
	</div>
</div>

<style type="text/css">
	.End {
		font-size: 40px;
	}
</style>

<div class="center">
	<form method="POST">
		{% csrf_token %}
		{{form.as_table}}
		<div class="buttons text-center">
			<!-- <button type='submit'><a class="waves-effect waves-light btn-large"><div class="End">End Game</div></a></button> -->
			<a href='/endGame?gameCode={{Game.game_code}}' class="waves-effect waves-light btn-large">
				<div class="End">End Game</div>
			</a>
		</div>
	</form>

</div>

<script type="text/javascript">






	let butnSub = document.querySelector(".End");

	butnSub.addEventListener('click', sendResult);

	function sendResult() {
		fetch("{% url 'main:gamePlay' %}", {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ "redTeam": redTeam, "blueTeam": blueTeam, "gameCode": "{{Game.game_code}}" })
		})
	}



</script>
{% endblock %}

FQhStatsKeepr/main/templates/main/header.html
<head>
    {% load static %}
    <!-- Prism CSS -->
    <!-- <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet"> -->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <nav>
      <nav>
    <div class="nav-wrapper grey darken-4">
      <a href="/" class="brand-logo"><img src = "{% static 'main/images/fqhlogotranswdes.png' %}" width = "150"></a>
      <ul class="right hide-on-med-and-down">
        <li><a a href="/" class="waves-effect waves-light btn grey lighten-2"> <span class = "black-text"> Games Played </span></a></li>
        <li><a a href ="/playerStats" class="waves-effect waves-light btn grey lighten-2"><span class = "black-text"> Player Stats</span></a></li>
        <li><a href='/newGame' class="waves-effect waves-light btn grey lighten-2"><span class = "black-text"> New Game</span></a></li>  
      </ul>
    </div>
  </nav>
  </nav>
  {% block content %}
  {% endblock %}
</body>

<!-- Prism JS -->
<!-- <script src="{% static 'tinymce/js/prism.js' %}"></script> -->
<!-- <script src="{% static 'main/js/app.js' %}"></script> -->

FQhStatsKeepr/main/templates/main/home.html
{% extends 'main/header.html' %}
{% load static %}
{% block content %}
<div class="row">

  {% for game in Games %}
  <div class="col s6 m8 l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
        <span class="card-title">{{game.game_Date}} | R {{game.teamRed_score}} - B {{game.teamBlue_score}} </span>
        <p>{% for k,v in game.teamRed_players.items %} {{v}}, {% endfor %}{% for k,v in game.teamBlue_players.items %} {{v}}, {% endfor %}</p>
      </div>
      <div class="card-action">
        <a href='/endGame?gameCode={{game.game_code}}'>Scoresheet</a>
      </div>
    </div>
  </div>
    {% endfor %}

</div>


{% endblock %}

FQhStatsKeepr/main/templates/main/nav.html
{% block content %}
 <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">FQH</a>
      <ul class="right hide-on-med-and-down">
        <li><a class="waves-effect waves-light btn">Button</a></li>
        <li><a class="waves-effect waves-light btn">Button <i class="material-icons right">cloud</i></a></li>
        <li><a class="waves-effect waves-light btn-large">Large Button</a></li>
      </ul>
    </div>
  </nav>
{% endblock %}

FQhStatsKeepr/main/templates/main/playerStats.html
{% extends 'main/header.html' %}

{% block content %}
{% load static %}
<div class= "container">
    <h1>Check back soon</h1>
</div>
{% endblock %}